---
abstract: 'Simplified object abstraction over Win32::File'
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.85'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Win32::File::Object
name: Win32-File-Object
no_index:
  directory:
    - inc
    - t
requires:
  File::Remove: 0.38
  File::Spec: 0.80
  Win32::File: 0.05
  perl: 5.6.0
resources:
  ChangeLog: http://fisheye2.atlassian.com/changelog/cpan/trunk/Win32-File-Object
  license: http://dev.perl.org/licenses/
  repository: http://svn.ali.as/cpan/trunk/Win32-File-Object
version: 0.02
