---
name: Win32-File-Object
version: 0.01
abstract: Simplified object abstraction over Win32::File
author: Adam Kennedy <adamk@cpan.org>
distribution_type: module
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.006
  Win32::File: 0.05
build_requires:
  File::Spec: 0.80
  File::Remove: 0.38
  Test::More: 0.42
